#!/usr/bin/env node
/* eslint-disable import/no-commonjs, no-console */
const fs = require('fs');
const postcss = require('postcss');
const atImport = require('postcss-import');
const rmComments = require('postcss-discard-comments');

const input = './src/main.css';

const css = fs.readFileSync(input, 'utf8');
const plugins = [atImport(), rmComments()];

postcss(plugins)
  .process(css, {
    from: input,
  })
  .then(result => {
    fs.writeFileSync('build/tachyons-algolia.css', result.css);
  });
// console.info(css);

// # mkdir -p ./build
// #
// # # Building normal version
// # # node-sass ./src/main.scss ./build/tachyons-algolia.css
// #
// # # Building compressed version
// # cleancss \
// #   -O1 \
// #   -o ./build/tachyons-algolia.min.css \
// #   ./build/tachyons-algolia.css
