#!/usr/bin/env sh

# Tachyons
mkdir -p ./src/vendors/tachyons
cp \
  -r \
 ./node_modules/tachyons-sass/scss/ \
 ./src/vendors/tachyons
cp \
 ./node_modules/tachyons-sass/tachyons.scss \
 ./src/vendors/tachyons/_tachyons.scss

# FontAwesome
mkdir -p ./src/vendors/font-awesome
cp \
  -r \
 ./node_modules/font-awesome/scss/* \
 ./src/vendors/font-awesome

