#!/usr/bin/env sh

# Tachyons
rm -rf ./src/vendors/tachyons
mkdir -p ./src/vendors/tachyons
cp \
  -r \
 ./node_modules/tachyons/src/* \
 ./src/vendors/tachyons

# FontAwesome
cp \
  -rf \
 ./node_modules/font-awesome/fonts/* \
 ./src/fonts

